[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
social = "EsNiAoa8UtvZ81e1um5KLmW79xTq8DzyKvX4nZAG9TL6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
